Repository DivaryOfficial/divary-iOS, pull requests merged in 2025-07, with the labels that each got.

#2 👷‍♂️ Add Auto merge yml
  .github/WorkFlows/autoMerge.yml
Labels: CI

#19 ♻️[Refactor] 로그북 뷰 일부 개선 및 체감 온도 입력 추가
  Divary/Resources/Assets.xcassets/LogBook/EnvironmentInput/EnvInput-더움.imageset/온도-42.svg
  Divary/Resources/Assets.xcassets/LogBook/EnvironmentInput/EnvInput-추움.imageset/온도-41.svg
  Divary/Resources/Assets.xcassets/LogBook/EnvironmentInput/체감온도/Contents.json
  Divary/Resources/Assets.xcassets/LogBook/EnvironmentInput/체감온도/EnvInput-templike-보통-블루.imageset/Contents.json
  Divary/Resources/Assets.xcassets/LogBook/EnvironmentInput/체감온도/EnvInput-templike-보통-블루.imageset/EnvInput-보통-블루.pdf
  Divary/Resources/Assets.xcassets/LogBook/EnvironmentInput/체감온도/EnvInput-templike-보통.imageset/Contents.json
  Divary/Resources/Assets.xcassets/LogBook/EnvironmentInput/체감온도/EnvInput-templike-보통.imageset/EnvInput-보통.pdf
  Divary/Resources/Assets.xcassets/LogBook/EnvironmentInput/체감온도/EnvInput-더움-블루.imageset/Contents.json
  Divary/Resources/Assets.xcassets/LogBook/EnvironmentInput/체감온도/EnvInput-더움-블루.imageset/EnvInput-더움-블루.pdf
  Divary/Resources/Assets.xcassets/LogBook/EnvironmentInput/체감온도/EnvInput-더움.imageset/Contents.json
  Divary/Resources/Assets.xcassets/LogBook/EnvironmentInput/체감온도/EnvInput-더움.imageset/EnvInput-더움.pdf
  Divary/Resources/Assets.xcassets/LogBook/EnvironmentInput/체감온도/EnvInput-추움-블루.imageset/Contents.json
  Divary/Resources/Assets.xcassets/LogBook/EnvironmentInput/체감온도/EnvInput-추움-블루.imageset/EnvInput-추움-블루.pdf
  Divary/Resources/Assets.xcassets/LogBook/EnvironmentInput/체감온도/EnvInput-추움.imageset/Contents.json
  Divary/Resources/Assets.xcassets/LogBook/EnvironmentInput/체감온도/EnvInput-추움.imageset/EnvInput-추움.pdf
  Divary/Resources/Assets.xcassets/LogBookPage/Section/DiveEnvironmentSection/visibility/Contents.json
  Divary/Resources/Assets.xcassets/LogBookPage/Section/DiveEnvironmentSection/visibility/mynaui_angry-circle.imageset/Contents.json
  Divary/Resources/Assets.xcassets/LogBookPage/Section/DiveEnvironmentSection/visibility/mynaui_angry-circle.imageset/mynaui_angry-circle.svg
  Divary/Resources/Assets.xcassets/LogBookPage/Section/DiveEnvironmentSection/visibility/mynaui_annoyed-circle.imageset/Contents.json
  Divary/Resources/Assets.xcassets/LogBookPage/Section/DiveEnvironmentSection/visibility/mynaui_annoyed-circle.imageset/mynaui_annoyed-circle.svg
  Divary/Resources/Assets.xcassets/LogBookPage/Section/DiveEnvironmentSection/visibility/mynaui_baby.imageset/Contents.json
  Divary/Resources/Assets.xcassets/LogBookPage/Section/DiveEnvironmentSection/visibility/mynaui_baby.imageset/mynaui_baby.svg
  Divary/Resources/Assets.xcassets/LogBookPage/Section/DiveEnvironmentSection/wheather/Contents.json
  Divary/Resources/Assets.xcassets/LogBookPage/Section/DiveEnvironmentSection/wheather/cloud-sun.imageset/Contents.json
  Divary/Resources/Assets.xcassets/LogBookPage/Section/DiveEnvironmentSection/wheather/cloud-sun.imageset/humbleicons_cloud-sun.svg
  Divary/Resources/Assets.xcassets/LogBookPage/Section/DiveEnvironmentSection/wheather/cloud.imageset/Contents.json
  Divary/Resources/Assets.xcassets/LogBookPage/Section/DiveEnvironmentSection/wheather/cloud.imageset/humbleicons_cloud.svg
  Divary/Resources/Assets.xcassets/LogBookPage/Section/DiveEnvironmentSection/wheather/rain.imageset/Contents.json
  Divary/Resources/Assets.xcassets/LogBookPage/Section/DiveEnvironmentSection/wheather/rain.imageset/humbleicons_rain.svg
  Divary/Resources/Assets.xcassets/LogBookPage/Section/DiveEnvironmentSection/wheather/sun.imageset/Contents.json
  Divary/Resources/Assets.xcassets/LogBookPage/Section/DiveEnvironmentSection/wheather/sun.imageset/meteor-icons_sun.svg
  Divary/Resources/Assets.xcassets/SvgIcon/diaryIcon/Contents.json
  Divary/Resources/Assets.xcassets/SvgIcon/diaryIcon/diaryMainIcon/Contents.json
  Divary/Resources/Assets.xcassets/SvgIcon/diaryIcon/diaryMainIcon/Photo.imageset/Contents.json
  Divary/Resources/Assets.xcassets/SvgIcon/diaryIcon/diaryMainIcon/Photo.imageset/Photo.svg
  Divary/Resources/Assets.xcassets/SvgIcon/diaryIcon/diaryMainIcon/fluent_sticker-12-regular.imageset/Contents.json
  Divary/Resources/Assets.xcassets/SvgIcon/diaryIcon/diaryMainIcon/fluent_sticker-12-regular.imageset/fluent_sticker-12-regular.svg
  Divary/Resources/Assets.xcassets/SvgIcon/diaryIcon/diaryMainIcon/humbleicons_pencil.imageset/Contents.json
  Divary/Resources/Assets.xcassets/SvgIcon/diaryIcon/diaryMainIcon/humbleicons_pencil.imageset/humbleicons_pencil.svg
  Divary/Resources/Assets.xcassets/SvgIcon/diaryIcon/diaryMainIcon/humbleicons_text.imageset/Contents.json
  Divary/Resources/Assets.xcassets/SvgIcon/diaryIcon/diaryMainIcon/humbleicons_text.imageset/humbleicons_text.svg
  Divary/Resources/Assets.xcassets/SvgIcon/diaryIcon/diaryTextIcon/Contents.json
  Divary/Resources/Assets.xcassets/SvgIcon/diaryIcon/diaryTextIcon/humbleicons_italic.imageset/Contents.json
  Divary/Resources/Assets.xcassets/SvgIcon/diaryIcon/diaryTextIcon/humbleicons_italic.imageset/humbleicons_italic.svg
  Divary/Resources/Assets.xcassets/SvgIcon/diaryIcon/diaryTextIcon/humbleicons_underline.imageset/Contents.json
  Divary/Resources/Assets.xcassets/SvgIcon/diaryIcon/diaryTextIcon/humbleicons_underline.imageset/humbleicons_underline.svg
  Divary/Resources/Assets.xcassets/SvgIcon/diaryIcon/diaryTextIcon/mi_strikethrough.imageset/Contents.json
  Divary/Resources/Assets.xcassets/SvgIcon/diaryIcon/diaryTextIcon/mi_strikethrough.imageset/mi_strikethrough.svg
  Divary/Resources/Assets.xcassets/SvgIcon/diaryIcon/diaryTextIcon/mingcute_font-size-line.imageset/Contents.json
  Divary/Resources/Assets.xcassets/SvgIcon/diaryIcon/diaryTextIcon/mingcute_font-size-line.imageset/mingcute_font-size-line.svg
  Divary/Resources/Assets.xcassets/SvgIcon/diaryIcon/iconamoon_close-thin.imageset/Contents.json
  Divary/Resources/Assets.xcassets/SvgIcon/diaryIcon/iconamoon_close-thin.imageset/iconamoon_close-thin.svg
  Divary/Sources/LogBook/EnvironmentInput/EnvironmentInputView.swift
  Divary/Sources/LogBook/LogBookPage/LogBookPageMock.swift
  Divary/Sources/LogBook/LogBookPage/LogBookPageModel.swift
  Divary/Sources/LogBook/LogBookPage/Section/DiveEnvironmentSection.swift
  Divary/Sources/LogBook/LogBookPage/Section/DiveEquipmentSection.swift
  Divary/Sources/LogBook/LogBookPage/Section/DiveParticipantsSection.swift
Labels: enhancement

#33 🐛 [Bug]다이어리 텍스트 적용 버그 해결 & 코드 일부 리팩터링
  Divary/Sources/ContentView.swift
  Divary/Sources/Diary/Components/DeletePopupView.swift
  Divary/Sources/Diary/Components/FooterItem.swift
  Divary/Sources/Diary/DiaryImageDeco/DiaryImageFrame.swift
  Divary/Sources/Diary/DiaryImageSelect/DiaryImageSelectView.swift
  Divary/Sources/Diary/DiaryMain/AttributedTextView.swift
  Divary/Sources/Diary/DiaryMain/DiaryMainView.swift
  Divary/Sources/Diary/DiaryMain/DiaryMainViewModel.swift
  Divary/Sources/Diary/DiaryMain/EditingTestBlockView.swift
  Divary/Sources/Diary/DiaryMain/FooterBar/FontAlignmentFooterBar.swift
  Divary/Sources/Diary/DiaryMain/FooterBar/FontFamilyFooterBar.swift
  Divary/Sources/Diary/DiaryMain/FooterBar/FontOptionRow/FontOptionRow.swift
  Divary/Sources/Diary/DiaryMain/FooterBar/FontSizeFooterBar.swift
  Divary/Sources/Diary/DiaryMain/FooterBar/MainFooterBar.swift
  Divary/Sources/Diary/DiaryMain/FooterBar/TextStyleFooterBar.swift
  Divary/Sources/Diary/DiaryMain/example.swift
  Divary/Sources/DivaryApp.swift
  Divary/Sources/LogBook/Input/DiveInputPageView.swift
  Divary/Sources/LogBook/Input/EnvironmentInputView.swift
  Divary/Sources/LogBook/Input/OverViewInputView.swift
  Divary/Sources/LogBook/Input/ParticipantsInputView.swift
  Divary/Sources/LogBook/Input/ProfileInputView.swift
  Divary/Sources/LogBook/LogBookMain/LogBookNavBar/LogBookCalender/CalenderNavBar.swift
  Divary/Sources/LogBook/LogBookMain/LogBookNavBar/LogBookNavBar.swift
  Divary/Sources/LogBook/LogBookPage/LogBookPageView.swift
  Divary/Sources/MyOcean/MyOceanOnBoarding.swift
  Divary/Sources/MyOcean/MyOceanView.swift
  Divary/Sources/MyOcean/SpeechBubble/RectangleSpeechBubble.swift
  Divary/Sources/MyOcean/SpeechBubble/RectangleTailSpeechBubble.swift
  Divary/Sources/MyOcean/SpeechBubble/RoundedTailSpeechBubble.swift
  Divary/Sources/MyOcean/SpeechBubble/ThoughtSpeechBubble.swift
  Divary/Sources/ReusableComponent/NumberInputField.swift
  Divary/Sources/ReusableComponent/TabSelector.swift
  Divary/Sources/ReusableComponent/TextInputField.swift
  Divary/Sources/Store/BottomSheetView.swift
  Divary/Sources/Store/ModalTopTab.swift
  Divary/Sources/Store/OceanThema Store Component/OceanThemaStoreComponent.swift
  Divary/Sources/Store/PetComponent/PetStoreComponents.swift
  Divary/Sources/Store/StoreMainView.swift
  Project.swift
Labels: bug
